FROM node:16-slim
MAINTAINER Kihoon Han <me@hoony9x.dev>

ENV API_V3_MYSQL_HOST ""
ENV API_V3_MYSQL_PORT ""
ENV API_V3_MYSQL_USER ""
ENV API_V3_MYSQL_PASSWD ""
ENV API_V3_MYSQL_DB ""
#ENV API_V3_MYSQL_CONNECTION_LIMIT "20"
#ENV API_V3_WAIT_FOR_CONNECTIONS "false"

ENV API_V3_JWT_SECRET_KEY ""
#ENV API_V3_JWT_ALGORITHM "HS512"

ENV API_V3_AES_KEY ""

COPY ./ .
RUN npm install
CMD ["npm", "start"]
